---
- name: Install X11 packages
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - xorg-server
      - xorg-xinit
      - rxvt-unicode
      - kdiff3
      - awesome
      - ttf-dejavu
      - chromium

- name: Create Awesome config directory
  become: yes
  become_user: "{{ username }}"
  file:
      path: ~/.config/awesome
      state: directory

# Possibly move to separate repo
- name: Setup Awesome WM
  become: yes
  become_user: "{{ username }}"
  copy:
      src: awesome-rc.lua
      dest: ~/.config/awesome/rc.lua

- name: Copy .xinitrc
  become: yes
  become_user: "{{ username }}"
  copy:
      src: xinitrc
      dest: ~/.xinitrc

- name: Install screen lock
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - slock
      - xautolock
  when: setup_screenlock | bool

- name: Patch xinitrc with xautolock
  become: yes
  become_user: "{{ username }}"
  patch:
      src: xinitrc-xautolock.patch
      dest: /home/jimmieh/.xinitrc
  when: setup_screenlock | bool


        #- name: Install sound packages
        #      name: "{{ item }}"
        #      state: present
        #  with_items:
        #      - alsa-utils
        #      - pulseaudio
        #        #- pavucontrol # only with x
        #  when: enable_sound | bool
