---
- name: Clone Vim environment
  become: yes
  become_user: "{{ username }}"
  git:
      repo: https://github.com/nomme/vim-env.git
      dest: ~/.vim
      recursive: yes

- name: Create vim autoload directory
  become: yes
  become_user: "{{ username }}"
  file:
      path: ~/.vim/autoload
      state: directory

- name: Setup vim-plug
  become: yes
  become_user: "{{ username }}"
  get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.vim/autoload/plug.vim

- name: Install plugins with vim-plug
  become: yes
  become_user: "{{ username }}"
  shell: vim +PlugInstall +qall

