---
- hosts: local
  remote_user: root
  vars_prompt:
    - name: "proxy"
      prompt: "Proxy"
      private: no
    - name: "username"
      prompt: "Username to add"
      default: jimmieh
      private: no
    - name: "devel_tools"
      prompt: "Install development tools"
      default: "no"
      private: no
    - name: "enable_ntp"
      prompt: "Install and enable NTP (1=yes)"
      default: "no"
      private: no
    - name: "enable_sound"
      prompt: "Install ALSA and PulseAudio (1=yes)"
      default: "no"
      private: no
    - name: "install_x"
      prompt: "Install X11 and other utils"
      default: "no"
      private: no
    - name: "setup_screenlock"
      prompt: "Setup lock screen"
      default: "no"
      private: no
      when: install_x | bool
    - name: "btrfs_progs"
      prompt: "Install Btrfs progs"
      default: "no"
      private: no
    - name: "install_wireshark"
      prompt: "Install Wireshark"
      default: "no"
      private: no

  environment:
    http_proxy: "{{proxy}}"
    https_proxy: "{{proxy}}"

  roles:
      - add_user
      - base_packages
      - vim_env
      - zsh_env
      - { role: x, when: install_x | bool }
      - { role: ntp, when: enable_ntp | bool }
      - networkmanager
      - bin_dir

